import threading
RECORDS_TO_ACQUIRE_PER_QUERY = 2
OVERRIDE_AVAILABILITY_CHECKS_ON_EARLY_REASKS = 0
SS_COUNTERS_LOCK = threading.Lock()
SS_REQUESTS_RECEIVED = 0
SS_REQUESTS_DIRECT = 0
NTP_CHECK_IS_EXPERIMENT = False
P2P_CHECK_IS_EXPERIMENT = False
PEER_HITS = 0
PEER_MISSES = 0
